export declare enum DependentRelationship {
    SELF = "Self",
    SPOUSE = "Spouse",
    FATHER = "Father",
    MOTHER = "Mother",
    BROTHER = "Brother",
    SISTER = "Sister",
    SON = "Son",
    DAUGHTER = "Daughter",
    STUDENT = "Student",
    CHILD = "Child",
    OTHER = "Other",
    MARRIED_CHILD = "Married Child",
    GRANDCHILD = "Grandchild",
    UNMARRIED_CHILD = "Unmarried Child",
    PARTNER = "Partner",
    PARENT = "Parent",
    SUBSCRIBER = "Subscriber",
}
