export interface Auth {
    /**
     * The OAUTH token generated by the login API
     */
    accessToken: string;
    /**
     * The JWT token generated by the authentication token.
     */
    idToken: string;
    /**
     * The refresh token used for generated a new accessToken
     */
    refreshToken: string;
    /**
     * The expiry time (provided as a timestamp / 1000) of the access token.
     * Once this has expired, the refresh token should be used to renew the token.
     */
    expiry: number;
    /**
     * The ID used to identify the local application.
     */
    clientId: string;
    /**
     * The user's unique ID
     */
    userId: string;
    /**
     * The user's vHealth individual ID
     */
    individualId: string;
    /**
     * If the journey is login or register
     */
    journey: string;
    /**
     * Converted status
     */
    converted: string;
}
